/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham/$slug'
import { Route as LandingPageSlugRouteImport } from './routes/landing-page/$slug'
import { Route as DanhMucSanPhamSlugRouteImport } from './routes/danh-muc-san-pham/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/san-pham/$slug',
  path: '/san-pham/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageSlugRoute = LandingPageSlugRouteImport.update({
  id: '/landing-page/$slug',
  path: '/landing-page/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhMucSanPhamSlugRoute = DanhMucSanPhamSlugRouteImport.update({
  id: '/danh-muc-san-pham/$slug',
  path: '/danh-muc-san-pham/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/danh-muc-san-pham/$slug': typeof DanhMucSanPhamSlugRoute
  '/landing-page/$slug': typeof LandingPageSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/danh-muc-san-pham/$slug': typeof DanhMucSanPhamSlugRoute
  '/landing-page/$slug': typeof LandingPageSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/danh-muc-san-pham/$slug': typeof DanhMucSanPhamSlugRoute
  '/landing-page/$slug': typeof LandingPageSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/danh-muc-san-pham/$slug'
    | '/landing-page/$slug'
    | '/san-pham/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/danh-muc-san-pham/$slug'
    | '/landing-page/$slug'
    | '/san-pham/$slug'
  id:
    | '__root__'
    | '/'
    | '/danh-muc-san-pham/$slug'
    | '/landing-page/$slug'
    | '/san-pham/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DanhMucSanPhamSlugRoute: typeof DanhMucSanPhamSlugRoute
  LandingPageSlugRoute: typeof LandingPageSlugRoute
  SanPhamSlugRoute: typeof SanPhamSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/san-pham/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page/$slug': {
      id: '/landing-page/$slug'
      path: '/landing-page/$slug'
      fullPath: '/landing-page/$slug'
      preLoaderRoute: typeof LandingPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-muc-san-pham/$slug': {
      id: '/danh-muc-san-pham/$slug'
      path: '/danh-muc-san-pham/$slug'
      fullPath: '/danh-muc-san-pham/$slug'
      preLoaderRoute: typeof DanhMucSanPhamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DanhMucSanPhamSlugRoute: DanhMucSanPhamSlugRoute,
  LandingPageSlugRoute: LandingPageSlugRoute,
  SanPhamSlugRoute: SanPhamSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
